name: Test Self-Hosted Runner with Docker

on:
  push:
    branches:
      - main

jobs:
  docker-job:
    runs-on: self-hosted # Указываем использовать self-hosted runner

    steps:
      # Шаг 1. Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2. Создаем файл .env
      - name: Create .env file
        run: echo "$ENV_FILE" > .env
        env:
          ENV_FILE: |
            KEY=value
            ANOTHER_KEY=another_value

      # Шаг 3. Запускаем docker-compose
      - name: Run Docker Compose
        run: docker compose up -d --build
        
      # Шаг 4. Проверяем список контейнеров
      - name: List all Docker containers
        run: docker ps -a

      # Шаг 5. Завершаем работу контейнеров (опционально)
      - name: Stop and remove containers
        run: docker-compose -f docker-compose.yml down
